version: 2

# Group settings to apply to all groups by default, optionally being overridden later
group_defaults:
  approve_by_comment:
    enabled: true
    approve_regex: '(Approved|:shipit:|:\+1:|LGTM)'
  reset_on_push:
    enabled: true
  author_approval:
      auto: true

groups:
  maintainers:
    required: 3
    teams:
      - maintainers
