version: 2
groups:
  maintainers:
    required: 3
    author_approval:
      auto: true
    approve_by_comment: true
    approve_regex: '^(Approved|:shipit:|:\+1:|LGTM)'
    reject_regex: '^Rejected'
    reset_on_push: true
    teams:
      - maintainers
